# Generated by Django 4.0.4 on 2022-08-13 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0006_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='rasm',
        ),
    ]
